Use netlink headers instead of kernel headers
In file included from /usr/include/linux/rtnetlink.h:5,
                 from compat-suse.c:11:
/usr/include/linux/netlink.h:34: error: expected specifier-qualifier-list before 'sa_family_t'